apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: trading-assistant
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/willhumphreys/trading-assistant
  ref:
    branch: terraform-updates