apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  labels:
    release: prometheus-kafka-exporter  # This label should match your Prometheus Operator's selector
spec:
  selector:
    matchLabels:
      app: prometheus-kafka-exporter
      release: prometheus-kafka-exporter
  endpoints:
    - port: exporter-port  # Name of the port in the kafka-exporter service
      path: /metrics
      interval: 10s
